[versions]
paper = "1.20.2-R0.1-SNAPSHOT"
adventure = "4.14.0"
annotations = "24.0.1"

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.+" }
spotless = { id = "com.diffplug.spotless", version = "6.+" }
runPaper = { id = "xyz.jpenilla.run-paper", version = "2.1.0" }
